### ISSUE TITLE
[Feature] Migrate the production environment to host 147 and migrate the development environment to host 146

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ServerSwarm#33]
# context
| Host | situation before migration | domain before migration | domain after migration | Remarks |
| --- | --- | --- | --- | --- |
| 147 | isunfa 隨便測試的 branch | isunfa.tw | isunfa.com | 新機器，先用 [isunfa.tw](http://isunfa.tw)  （develop） 練手，需要改成 [isunfa.com](http://isunfa.com)  （main） |
| 146 | AICH production | aich.isunfa.com | isunfa.tw | 舊機器，正在運行 [aich.isunfa.com](http://aich.isunfa.com) ，需要改成 [isunfa.tw](http://isunfa.tw) (develop) |

# todo
### migrate production environment

- [x]  在 147 修改 db 參數，改名 production
- [x]  將 147 的 ./isunfa/app ./faith/app ./aich/app 刪掉，.env 的 target branch 都改成 main
- [x]  關掉 146 的 AICH
- [x]  在域名註冊商網站，將 [isunfa.com](http://isunfa.com) domain 指向 147 主機
- [x]  更改 147 domain 參數
- [x]  在 147 重啟 docker
- [x]  確認 147 可以正常運作 isunfa main branch 之後再去處理 146 運行 isunfa develop branch

---

### migrate dev environment

- [x]  準備好要放在 146 主機的參數
- [x]  在 146 上 clone ServerSwarm repo，checkout develop branch，填好 main bracnh 參數之後跑看看 docker compose
    - 146 的 postgres env 要改
- [x]  將 media data 搬到 146 上
- [x]  將 db 備份到 146 的 postgres docker container 裡，然後跑 docker compose 確認功能正常，確認完之後先關掉 docker container
- [x]  在域名註冊商網站，將 [isunfa.tw](http://isunfa.tw) domain 指向 146 主機
- [x]  將 146 的 ./isunfa/app ./faith/app ./aich/app 刪掉，.env 的 target branch 都改成 develop
- [x]  在 146 重啟 docker

**Comment by arealclimber** [comment]
took 4 hrs
done
